// Türkiye'deki başlıca Organize Sanayi Bölgeleri (il → OSB). Tıklanan OSB için kampanya açılır, listeden gizlenir.
const L = {
  'İstanbul': ['İkitelli OSB', 'Dudullu OSB', 'Tuzla Kimya Sanayicileri OSB', 'İstanbul Deri OSB (Tuzla)', 'Beylikdüzü OSB', 'İstanbul Anadolu Yakası OSB (Tuzla)'],
  'Kocaeli': ['Gebze OSB (GOSB)', 'Gebze Güzeller OSB', 'Gebze Plastikçiler OSB', 'Dilovası OSB', 'TOSB Otomotiv Yan Sanayi OSB (Çayırova)', 'İMES OSB (Dilovası)', 'Arslanbey OSB (Kartepe)', 'Asım Kibar OSB (Kartepe)', 'Gebze Kömürcüler OSB'],
  'Sakarya': ['Sakarya 1. OSB', 'Sakarya 2. OSB (Hendek)'],
  'Bursa': ['Bursa OSB (BOSB)', 'Nilüfer OSB (NOSAB)', 'Demirtaş OSB (DOSAB)', 'İnegöl OSB', 'Bursa Deri OSB', 'Hasanağa OSB', 'Kayapa OSB', 'Gürsu OSB', 'Kestel OSB', 'Yenişehir OSB'],
  'Ankara': ['OSTİM OSB', 'İvedik OSB', 'Ankara Sanayi Odası 1. OSB (Sincan)', 'Anadolu OSB (Malıköy)', 'Başkent OSB'],
  'İzmir': ['Atatürk OSB (Çiğli)', 'Kemalpaşa OSB', 'Pancar OSB (Torbalı)', 'İTOB OSB (Menderes)', 'Tire OSB', 'Aliağa Kimya İhtisas OSB', 'Menemen Plastik İhtisas OSB'],
  'Manisa': ['Manisa OSB', 'Turgutlu OSB', 'Akhisar OSB', 'Salihli OSB'],
  'Tekirdağ': ['Çerkezköy OSB', 'Velimeşe OSB (Çorlu)', 'Ergene 1. OSB', 'Ergene 2. OSB'],
  'Konya': ['Konya OSB', 'Konya Ereğli OSB'],
  'Kayseri': ['Kayseri OSB', 'Kayseri Mimarsinan OSB', 'Kayseri İncesu OSB'],
  'Gaziantep': ['Gaziantep OSB (Başpınar)'],
  'Eskişehir': ['Eskişehir OSB'],
  'Denizli': ['Denizli OSB'],
  'Adana': ['Adana Hacı Sabancı OSB'],
  'Mersin': ['Mersin Tarsus OSB'],
  'Balıkesir': ['Balıkesir OSB'],
  'Bilecik': ['Bilecik OSB', 'Bozüyük OSB'],
  'Düzce': ['Düzce 1. OSB'],
  'Kütahya': ['Kütahya OSB'],
  'Afyonkarahisar': ['Afyonkarahisar OSB'],
  'Uşak': ['Uşak OSB'],
  'Çorum': ['Çorum OSB'],
  'Samsun': ['Samsun Merkez OSB'],
  'Kahramanmaraş': ['Kahramanmaraş OSB'],
  'Malatya': ['Malatya OSB'],
  'Karaman': ['Karaman OSB'],
  'Aksaray': ['Aksaray OSB'],
  'Sivas': ['Sivas OSB'],
  'Trabzon': ['Arsin OSB'],
  'Osmaniye': ['Osmaniye OSB'],
  'Antalya': ['Antalya OSB'],
  'Şanlıurfa': ['Şanlıurfa OSB'],
  'Diyarbakır': ['Diyarbakır OSB'],
  'Elazığ': ['Elazığ OSB'],
};
const list = () => Object.entries(L).flatMap(([city, xs]) => xs.map(name => ({ city, name, key: `${city}|${name}` })));
module.exports = { list, L };
